version: '2'

services:
  nginx:
    image: "nginx:${NGINX_IMAGE_TAG}"
    container_name: "nginx"
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - "/etc/nginx/conf.d"
      - "./certs:/etc/nginx/certs:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - "nginx-network"

  letsencrypt-nginx-companion:
    image: "jrcs/letsencrypt-nginx-proxy-companion:${LETSENCRYPT_NGINX_COMPANION_IMAGE_TAG}"
    container_name: "nginx-letsencrypt"
    volumes_from:
      - "nginx"
    volumes:
      - "./certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "NGINX_DOCKER_GEN_CONTAINER=nginx-gen"
    networks:
      - "nginx-network"

  dockergen:
    image: "jwilder/docker-gen:${DOCKERGEN_IMAGE_TAG}"
    container_name: "nginx-dockergen"
    command: "-notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    volumes_from:
      - "nginx"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl"
    networks:
      - "nginx-network"

networks:
  nginx-network:
    external:
      name: "${NGINX_EXTERNAL_NETWORK_NAME}"
